apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
    namespace: default
type: Opaque
stringData:
    MONGO_DB_HOST: ENC[AES256_GCM,data:/VQt219L925o,iv:8qAWGhIYMkdok5rbIDS1VpFCnQKml94voTdxV+msigc=,tag:WzbtXQCDJHR7pG2KeAFfeg==,type:str]
    MONGO_DB_PORT: ENC[AES256_GCM,data:Yq0il4Y=,iv:j5X5akIPVpqPN0hLwjaLbJHQ4K0XrOsdpGRLKpA1+f8=,tag:xy6MCNPe/Tb2DyuZZ8zK/g==,type:str]
    MONGO_USER: ENC[AES256_GCM,data:wkGQB8w=,iv:MNmv/p9XjB97Ds1dljkMCCpocIudV0AoF7Tr6ACjXiM=,tag:STEuruxnjxGbTKE1V9fjCw==,type:str]
    MONGO_PASSWORD: ENC[AES256_GCM,data:/483J+lq,iv:/S2acfb2rQ4hVMs5aOcHq8K6pWsoPECtP7uOAU2AcWM=,tag:3x8cJJZ6LWOuhG3LMf/0Lw==,type:str]
    MONGO_DB_NAME: ENC[AES256_GCM,data:mC3+etBO,iv:3AVh9DIujl9qcJW2vng+UViJIkfYEGKYwl/Xz5hglhs=,tag:+Xb5552UUpnaYPTN5LNlbQ==,type:str]
sops:
    age:
        - recipient: age1jmdc7mka2ytd0nzwartj56fe0hnlfpuec045h3kmr3lpz5quwa9sycpe0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VE5GbFpVNEc2V1dnZVpy
            elpNdDFnL2F1bUZUR3k3b21iK0I4WkZ2WG1ZCk52NmRFaE5YWU54NGFXYUNzemla
            Tm9iM1g2eDVld0pDQW1HQWYyKzUzdzgKLS0tIC8yNHc3WE1haUNhaGdmZzJ1WU4y
            UE92STFzWUJBc0U4T25hQis5dkgxMFUK22D+r5ux3IQoWvEylEZFrp801/VOsU8/
            yii9vtv5GgDWgIuUN98pg92W26lxn0VqOiGO4I7OvqRY4cM8mKr5/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T16:34:29Z"
    mac: ENC[AES256_GCM,data:cW/C6GlGw0mbzE7AX6aId2CKmZjPCvDpy/r1LAnigPxRS9f6+0pG/d0TJ5JXnj0e+c1sah83Dh88SY/ZPzS7rPq457CgwqDsSsOvW/uYNh30Dp84hpI3IJRhBpfZtyxaRECprcyT7FTzn6hr3EPwI4mG//wDf22Pd1wNiTpPcjc=,iv:LqLqxc/jlbgz+GR13R4iuREou/s8lYTkgrfmo0+4f04=,tag:2zF26AbeoTQJZ3y0t4UjIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
